// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface Metrics { files_excluded: number, files_included: number, last_excluded: string, last_excluded_time: number, }