// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PreDirectory } from "./PreDirectory";
import type { PreRule } from "./PreRule";

export interface PreConfig { "no-include": boolean, directories: Array<PreDirectory>, skips: Array<string>, rules: Record<string, PreRule>, }