// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExclusionActionBatch } from "./ExclusionActionBatch";

export type ScanStatus = { step: "idle" } | { step: "scanning", content: { current_path: string, found: number, } } | { step: "result", content: ExclusionActionBatch };