// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExclusionActionBatch } from "./ExclusionActionBatch";

export type ScanStatus = "Idle" | { Scanning: string } | { Result: ExclusionActionBatch };